import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Codelab Next.js 2nd Librery
        </h1>

        <p className={styles.description}>
          코드랩 Next.js 2기 수업을 통해 나온 산출물입니다.{' '}
        </p> 
        <div className='text-center'>
        <button className='btn btn-primary btn-large'>
          바로 시작하기
        </button>
        </div>
      </main>

    </div>
  )
}
